## numpy notes and scratchpad

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
a[0]

1

In [5]:
print('a    == {}'.format(a))
print('a[0] == {}'.format(a[0]))
print('a[1] == {}'.format(a[1]))
print('a[2] == {}'.format(a[2]))

a    == [1 2 3]
a[0] == 1
a[1] == 2
a[2] == 3


In [6]:
matrix[1, 1]

5

In [7]:
matrix[2, 2]

9

In [8]:
matrix[1:, :2]

array([[4, 5],
       [7, 8]])

In [9]:
matrix[:1]

array([[1, 2, 3]])

In [10]:
matrix[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
matrix[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
matrix[2:]

array([[7, 8, 9]])

In [13]:
should_include_elements = [True, False, True]
a[should_include_elements]

array([1, 3])

In [14]:
original_array = [1, 2, 3, 4, 5]
array_with_one_added = []
for n in original_array:
    array_with_one_added.append(n + 1)
print(array_with_one_added)

[2, 3, 4, 5, 6]


In [15]:
original_array = [1, 2, 3, 4, 5]
array_with_one_added = [n + 1 for n in original_array]
print(array_with_one_added)

[2, 3, 4, 5, 6]


In [16]:
original_array = np.array([1, 2, 3, 4, 5])
original_array + 1

array([2, 3, 4, 5, 6])

In [17]:
original_array * 2

array([ 2,  4,  6,  8, 10])

In [18]:
original_array

array([1, 2, 3, 4, 5])

In [19]:
my_array = np.array([-3, 0, 3, 16])

print('my_array      == {}'.format(my_array))
print('my_array - 5  == {}'.format(my_array - 5))
print('my_array * 4  == {}'.format(my_array * 4))
print('my_array / 2  == {}'.format(my_array / 2))
print('my_array ** 2 == {}'.format(my_array ** 2))
print('my_array % 2  == {}'.format(my_array % 2))

my_array      == [-3  0  3 16]
my_array - 5  == [-8 -5 -2 11]
my_array * 4  == [-12   0  12  64]
my_array / 2  == [-1.5  0.   1.5  8. ]
my_array ** 2 == [  9   0   9 256]
my_array % 2  == [1 0 1 0]


In [20]:
my_array = np.array([-3, 0, 3, 16])

print('my_array       == {}'.format(my_array))
print('my_array == -3 == {}'.format(my_array == -3))
print('my_array >= 0  == {}'.format(my_array >= 0))
print('my_array < 10  == {}'.format(my_array < 10))

my_array       == [-3  0  3 16]
my_array == -3 == [ True False False False]
my_array >= 0  == [False  True  True  True]
my_array < 10  == [ True  True  True False]


In [21]:
my_array[my_array > 0]

array([ 3, 16])

In [22]:
my_array[my_array < 0]

array([-3])

In [23]:
my_array[my_array % 2 == 0]

array([ 0, 16])

In [24]:
my_array[my_array % 2 == 1]

array([-3,  3])

In [25]:
np.random.randn(10)

array([-2.10295627,  0.14290591, -1.42217125, -0.27539584,  0.48657372,
        0.4410396 , -0.2101968 , -1.0226378 , -0.45532815, -0.56471808])

In [26]:
np.random.randn(3, 4)

array([[ 1.17912993, -0.48499705, -0.09144671,  1.0312122 ],
       [ 1.77312403, -1.1751171 ,  2.11983219,  0.77863117],
       [ 0.63314012,  0.32411693, -0.56558049,  0.45944431]])

In [27]:
np.arange(4)

array([0, 1, 2, 3])

In [29]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [30]:
a.min()

1

In [31]:
a.max()

5

In [32]:
a.mean()

3.0

In [33]:
a.sum()

15

In [34]:
a.std()

1.4142135623730951

In [35]:
a.std() ** 2

2.0000000000000004

In [36]:
a < 0

array([False, False, False, False, False])

In [37]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [40]:
len(a[a<0])

4

In [39]:
a[a>=0]

array([ 4, 10, 12, 23,  0,  0,  0,  3])

In [51]:
b = len(a[a % 2 == 0])
len([b >= 0])

1

In [63]:
len(a[a % 2 == 0]) 

8

In [56]:
(a[a % 2 == 0]) 


array([ 4, 10, 12, -2,  0,  0,  0, -6])

In [167]:
step_1 = (a[a % 2 == 0]) 
step_2 = step_1 > 0
step_1[step_2]

array([ 2,  4,  6,  8, 10])

In [79]:
len(a[a % 2 == 0]) 


8

In [88]:
step_a = a + 3
step_b = len(a[a >= 0])
step_b

array([ 4, 10, 12, 23,  0,  0,  0,  3])

In [90]:
a ** 2
a.mean
a.std


<function ndarray.std>

In [91]:
a ** 2

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [101]:
step_sq = a ** 2
step_mn = step_sq.mean
step_std = step_sq.std


step_std()

144.0243035046516

In [103]:
a.mean()

3.0

In [107]:
np.mean(a) # calculates the mean of the array x


3.0

In [108]:
a - a.mean()

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [113]:
from scipy import stats

stats.zscore(a)


array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [114]:
a.sum

<function ndarray.sum>

In [123]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [124]:
def sum_of_a(x):
    x = a.sum
print(sum_of_a)

<function sum_of_a at 0x7f8e236dddc0>


In [125]:
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [133]:
a.sum()

55

In [132]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
sum_of_a = a.sum()
print("The sum of a is", sum_of_a)

The sum of a is 55


In [134]:
min_of_a = a.min()

print("The min of a is", min_of_a)

The min of a is 1


In [135]:
max_of_a = a.max()

print("The max of 'a' is", max_of_a)

The max of 'a' is 10


In [139]:
np.prod(np.array(a))  

3628800

In [140]:
squares_of_a = a ** 2

print("The squares of 'a' are", squares_of_a)

The squares of 'a' are [  1   4   9  16  25  36  49  64  81 100]


In [150]:
odds_in_a = (a[a % 2 == 1])

print("The odds in a are", odds_in_a)

The odds in a are [1 3 5 7 9]


In [154]:
evens_in_a = (a[a % 2 == 0])

print("The evens in 'a' are", evens_in_a)

The evens in 'a' are [ 2  4  6  8 10]


In [155]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]

# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

print("The sum of 'b' is", sum_of_b)

The sum of 'b' is 33


In [156]:
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

print("The min of 'b' is", min_of_b)

The min of 'b' is 3


In [158]:
np.b = [
    [3, 4, 5],
    [6, 7, 8]
]

print(np.b)

[[3, 4, 5], [6, 7, 8]]


In [164]:
(a < 0).sum()


0

In [165]:
np.count_nonzero(a < 0)

0