## numpy notes and scratchpad

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
a[0]

1

In [5]:
print('a    == {}'.format(a))
print('a[0] == {}'.format(a[0]))
print('a[1] == {}'.format(a[1]))
print('a[2] == {}'.format(a[2]))

a    == [1 2 3]
a[0] == 1
a[1] == 2
a[2] == 3


In [6]:
matrix[1, 1]

5

In [7]:
matrix[2, 2]

9

In [8]:
matrix[1:, :2]

array([[4, 5],
       [7, 8]])

In [9]:
matrix[:1]

array([[1, 2, 3]])

In [10]:
matrix[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
matrix[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
matrix[2:]

array([[7, 8, 9]])

In [13]:
should_include_elements = [True, False, True]
a[should_include_elements]

array([1, 3])

In [14]:
original_array = [1, 2, 3, 4, 5]
array_with_one_added = []
for n in original_array:
    array_with_one_added.append(n + 1)
print(array_with_one_added)

[2, 3, 4, 5, 6]


In [16]:
original_array = [1, 2, 3, 4, 5]
array_with_one_added = [n + 1 for n in original_array]
print(array_with_one_added)

[2, 3, 4, 5, 6]


In [17]:
original_array = np.array([1, 2, 3, 4, 5])
original_array + 1

array([2, 3, 4, 5, 6])

In [18]:
original_array * 2

array([ 2,  4,  6,  8, 10])

In [19]:
original_array

array([1, 2, 3, 4, 5])

In [22]:
my_array = np.array([-3, 0, 3, 16])

print('my_array      == {}'.format(my_array))
print('my_array - 5  == {}'.format(my_array - 5))
print('my_array * 4  == {}'.format(my_array * 4))
print('my_array / 2  == {}'.format(my_array / 2))
print('my_array ** 2 == {}'.format(my_array ** 2))
print('my_array % 2  == {}'.format(my_array % 2))

my_array      == [-3  0  3 16]
my_array - 5  == [-8 -5 -2 11]
my_array * 4  == [-12   0  12  64]
my_array / 2  == [-1.5  0.   1.5  8. ]
my_array ** 2 == [  9   0   9 256]
my_array % 2  == [1 0 1 0]


In [23]:
my_array = np.array([-3, 0, 3, 16])

print('my_array       == {}'.format(my_array))
print('my_array == -3 == {}'.format(my_array == -3))
print('my_array >= 0  == {}'.format(my_array >= 0))
print('my_array < 10  == {}'.format(my_array < 10))

my_array       == [-3  0  3 16]
my_array == -3 == [ True False False False]
my_array >= 0  == [False  True  True  True]
my_array < 10  == [ True  True  True False]


In [24]:
my_array[my_array > 0]

array([ 3, 16])

In [25]:
my_array[my_array < 0]

array([-3])

In [26]:
my_array[my_array % 2 == 0]

array([ 0, 16])

In [27]:
my_array[my_array % 2 == 1]

array([-3,  3])

In [28]:
np.random.randn(10)

array([ 0.77581687,  0.59413633,  1.38039785, -0.31173042,  0.7368572 ,
        1.00144333,  2.46257552,  0.60732114, -0.84668362, -1.27606781])

In [29]:
np.random.randn(3, 4)

array([[ 1.73807865,  0.51448365,  1.57496765,  0.64689373],
       [-0.84639319, -1.09903244, -1.93752755,  1.14263956],
       [ 0.34470301,  0.52307909, -0.61029369, -1.31801627]])

In [30]:
np.arange(4)

array([0, 1, 2, 3])

In [32]:
array[array + 2]

NameError: name 'array' is not defined

In [34]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [35]:
a.min()

1

In [36]:
a.max()

5

In [37]:
a.mean()

3.0

In [39]:
a.sum()

15

In [40]:
a.std()

1.4142135623730951

In [42]:
a.std() ** 2

2.0000000000000004